package Aplikasi;

import Config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DARMAWAN
 */
public class FormLogin extends javax.swing.JFrame {
    
    private Connection conn;
    private static boolean mulai;
    private static String admin;

    // getter mulai
    public static boolean isMulai() {
        return mulai;
    }
    
    // setter mulai
    public static void setMulai(boolean mulai) {
        FormLogin.mulai = mulai;
    }
    
    // getter admin
    public static String getAdmin() {
        return admin;
    }
    
    // setter admin
    public static void setAdmin(String admin) {
        FormLogin.admin = admin;
    }
    
    public FormLogin() {
        initComponents();
        
        conn = Koneksi.getKoneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        pnlJudul = new javax.swing.JPanel();
        lblSubjudul = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        pnlPass = new javax.swing.JPanel();
        lblPass = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        pnlAdmin = new javax.swing.JPanel();
        lblIDAdmin = new javax.swing.JLabel();
        txtIDAdmin = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        cbShowPass = new javax.swing.JCheckBox();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Login");
        setResizable(false);

        panelBackground.setPreferredSize(new java.awt.Dimension(800, 500));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlJudul.setBackground(new java.awt.Color(255, 255, 255));

        lblSubjudul.setBackground(new java.awt.Color(204, 204, 204));
        lblSubjudul.setText("\"Aplikasi Persediaan Buku\"");

        lblJudul.setBackground(new java.awt.Color(204, 204, 204));
        lblJudul.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(183, 132, 80));
        lblJudul.setText("LIBRABOOK");

        javax.swing.GroupLayout pnlJudulLayout = new javax.swing.GroupLayout(pnlJudul);
        pnlJudul.setLayout(pnlJudulLayout);
        pnlJudulLayout.setHorizontalGroup(
            pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJudulLayout.createSequentialGroup()
                .addGroup(pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJudulLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblJudul))
                    .addGroup(pnlJudulLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblSubjudul)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlJudulLayout.setVerticalGroup(
            pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJudulLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubjudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBackground.add(pnlJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 330, 80));

        pnlPass.setBackground(new java.awt.Color(255, 255, 255));
        pnlPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0)));

        lblPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/padlock.png"))); // NOI18N

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setText("Password");
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlPassLayout = new javax.swing.GroupLayout(pnlPass);
        pnlPass.setLayout(pnlPassLayout);
        pnlPassLayout.setHorizontalGroup(
            pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPassLayout.setVerticalGroup(
            pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPass)
                .addContainerGap(9, Short.MAX_VALUE))
            .addComponent(txtPassword)
        );

        panelBackground.add(pnlPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 340, 40));

        pnlAdmin.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0)));

        lblIDAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        txtIDAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIDAdmin.setText("ID Admin");
        txtIDAdmin.setBorder(null);
        txtIDAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDAdminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDAdminFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIDAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtIDAdmin, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lblIDAdmin)
                .addContainerGap())
        );

        panelBackground.add(pnlAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 340, 40));

        btnLogin.setBackground(new java.awt.Color(186, 133, 80));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelBackground.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 340, 40));

        cbShowPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbShowPass.setForeground(new java.awt.Color(255, 255, 255));
        cbShowPass.setText("Show Password");
        cbShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPassActionPerformed(evt);
            }
        });
        panelBackground.add(cbShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 305, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        panelBackground.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 870, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDAdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDAdminFocusGained
        String id = txtIDAdmin.getText();
        if(id.equals("ID Admin")) {
            txtIDAdmin.setText("");
        }
    }//GEN-LAST:event_txtIDAdminFocusGained

    private void txtIDAdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDAdminFocusLost
        String id = txtIDAdmin.getText();
        if(id.equals("")) {
            txtIDAdmin.setText("ID Admin");
        }
    }//GEN-LAST:event_txtIDAdminFocusLost
    
    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        String pw = txtPassword.getText();
        if(pw.equals("Password")) {
            txtPassword.setText("");
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        String pw = txtPassword.getText();
        if(pw.equals("")) {
            txtPassword.setText("Password");
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String id = txtIDAdmin.getText();
        String pass = txtPassword.getText();
    
        // variable untuk menyimpan status login
        boolean loginSukses = false;
        
        // menggunakan try-with-resources untuk PreparedStatement dan ResultSet
        // menyiapkan resource untuk koneksi
        try {
            String sql = "SELECT * FROM admin WHERE id_admin = ? AND pw_admin = ?";
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setString(1, id);
                stmt.setString(2, pass);
                
                try (ResultSet rs = stmt.executeQuery()) {
                    if (rs.next()) {
                        loginSukses = true;
                        admin = rs.getString("nama_admin");
                    }
                }
            }
            
            // Mengecek status login
            if (loginSukses) {
                setMulai(true);
                JOptionPane.showMessageDialog(this, "Login Berhasil!");
                new FormMenuUtama().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Login gagal. Nama atau password salah!");
            }
        
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cbShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPassActionPerformed
        if(cbShowPass.isSelected()) {
            txtPassword.setEchoChar((char)0);
        } else {
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShowPassActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox cbShowPass;
    private javax.swing.JLabel lblIDAdmin;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblSubjudul;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlJudul;
    private javax.swing.JPanel pnlPass;
    private javax.swing.JTextField txtIDAdmin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
