package Aplikasi;

import Config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DARMAWAN
 */
public class FormAdmin extends javax.swing.JFrame {
    
    private Connection conn;
    
    public FormAdmin() {
        if(!FormLogin.isMulai()) {
            JOptionPane.showMessageDialog(this, "Anda harus login terlebih dahulu.");
            new FormLogin().setVisible(true);
            dispose();
            setUndecorated(true); // method ini dipanggil krn meskipun di dispose, title bar tetap terlihat
        } else {
            initComponents();
            
            conn = Koneksi.getKoneksi();
            getData();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        lblIDAdmin = new javax.swing.JLabel();
        txtIDAdmin = new javax.swing.JTextField();
        lblNamaAdmin = new javax.swing.JLabel();
        txtNamaAdmin = new javax.swing.JTextField();
        lblNoTelp = new javax.swing.JLabel();
        txtNoTelp = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblAlamat = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnPass = new javax.swing.JButton();
        lblPassBaru = new javax.swing.JLabel();
        txtPassBaru = new javax.swing.JPasswordField();
        lblPassConfirm = new javax.swing.JLabel();
        txtPassConfirm = new javax.swing.JPasswordField();
        lblJudul1 = new javax.swing.JLabel();
        cbShowPass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Admin");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        background.setBackground(new java.awt.Color(255, 204, 204));
        background.setMinimumSize(new java.awt.Dimension(0, 0));
        background.setPreferredSize(new java.awt.Dimension(800, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        background.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 6, -1, -1));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setText("Data Admin");
        background.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblIDAdmin.setText("ID Admin");
        background.add(lblIDAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, -1, -1));
        background.add(txtIDAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 81, 710, -1));

        lblNamaAdmin.setText("Nama Admin");
        background.add(lblNamaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 109, -1, -1));
        background.add(txtNamaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 131, 710, -1));

        lblNoTelp.setText("Nomor Telepon");
        background.add(lblNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 159, -1, -1));
        background.add(txtNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 181, 710, -1));

        lblEmail.setText("Email");
        background.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 209, -1, -1));
        background.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 231, 710, -1));

        lblAlamat.setText("Alamat Admin");
        background.add(lblAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 259, -1, -1));
        background.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 281, 710, -1));

        btnEdit.setBackground(new java.awt.Color(255, 255, 204));
        btnEdit.setText("EDIT");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        background.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 200, 30));

        btnPass.setBackground(new java.awt.Color(255, 255, 204));
        btnPass.setText("GANTI PASSWORD");
        btnPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassActionPerformed(evt);
            }
        });
        background.add(btnPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 200, 30));

        lblPassBaru.setText("Password Baru");
        background.add(lblPassBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 370, -1, -1));
        background.add(txtPassBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 390, 300, -1));

        lblPassConfirm.setText("Password Baru");
        background.add(lblPassConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 370, -1, -1));
        background.add(txtPassConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 390, 300, -1));

        lblJudul1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul1.setText("Ganti Password");
        background.add(lblJudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 320, -1, -1));

        cbShowPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbShowPass.setForeground(new java.awt.Color(255, 255, 255));
        cbShowPass.setText("Show Password");
        cbShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPassActionPerformed(evt);
            }
        });
        background.add(cbShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        getContentPane().add(background, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void getData() {
        try {
            String sql = "SELECT * FROM admin";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            
            if(rs.next()) {
                String idAdmin = rs.getString("id_admin");
                String nama = rs.getString("nama_admin");
                String noTelp = rs.getString("no_telp");
                String email = rs.getString("email");
                String alamat = rs.getString("alamat_admin");
                
                txtIDAdmin.setText(idAdmin);
                txtNamaAdmin.setText(nama);
                txtNoTelp.setText(noTelp);
                txtEmail.setText(email);
                txtAlamat.setText(alamat);  
                
                txtIDAdmin.setEditable(false);
            }
            rs.close();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Tidak dapat menampilkan database. Kesalahan: " + e.getMessage());
        }
    }
    
    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        FormMenuUtama utama = new FormMenuUtama();
        utama.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // mengambil data yang sudah diedit
        String idAdmin = txtIDAdmin.getText();
        String nama = txtNamaAdmin.getText();
        String noTelp = txtNoTelp.getText();
        String email = txtEmail.getText();
        String alamat = txtAlamat.getText();
        
        // jika data kosong, akan diberikan peringatan melalui msgbox
        if(idAdmin.isEmpty() || nama.isEmpty() || noTelp.isEmpty() || email.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh ada yang kosong.");
            return;
        }
        
        try {
            String sql = "UPDATE admin SET nama_admin = ?, no_telp = ?, email = ?, alamat_admin = ? WHERE id_admin = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, nama);
            stmt.setString(2, noTelp);
            stmt.setString(3, email);
            stmt.setString(4, alamat);
            stmt.setString(5, idAdmin);
            int rowUpdated = stmt.executeUpdate();
            if(rowUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Data Admin Berhasil Diedit!");
                getData();
                FormLogin.setAdmin(nama);
            }
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Tidak dapat mengedit data admin. Kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassActionPerformed
        // mengambil data yang sudah diedit
        String idAdmin = txtIDAdmin.getText();
        String passBaru = txtPassBaru.getText();
        String passConfirm = txtPassConfirm.getText();
        
        // jika data tidak diisi atau kosong, akan diberikan peringatan melalui msgbox
        if(idAdmin.isEmpty() || passBaru.isEmpty() || passConfirm.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh ada yang kosong.");
            return;
        } else if (passConfirm.equals(passBaru)) {
            try {
                String sql = "UPDATE admin SET pw_admin = ? WHERE id_admin = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, passBaru);
                stmt.setString(2, idAdmin);
                int rowUpdated = stmt.executeUpdate();
                if(rowUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Password Admin Berhasil Diganti!");
                    getData();
                }
                stmt.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Tidak dapat mengganti password admin. Kesalahan: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Password baru dan konfirmasi password tidak sama.");
            return;
        }
    }//GEN-LAST:event_btnPassActionPerformed

    private void cbShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPassActionPerformed
        if(cbShowPass.isSelected()) {
            txtPassBaru.setEchoChar((char)0);
        } else {
            txtPassBaru.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShowPassActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnPass;
    private javax.swing.JCheckBox cbShowPass;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblIDAdmin;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul1;
    private javax.swing.JLabel lblNamaAdmin;
    private javax.swing.JLabel lblNoTelp;
    private javax.swing.JLabel lblPassBaru;
    private javax.swing.JLabel lblPassConfirm;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIDAdmin;
    private javax.swing.JTextField txtNamaAdmin;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JPasswordField txtPassBaru;
    private javax.swing.JPasswordField txtPassConfirm;
    // End of variables declaration//GEN-END:variables
}
